grad_clip: 5.0
batch_type: folded
batch_size: 40
optim: adagrad
lm: seq_rnn
#optim: adam
#optim_conf:
#    lr: 0.0005
lm_conf:
    unit: 650
    nlayers: 2
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 1
